import type { Metadata } from "next";
import { Be_Vietnam_Pro } from "next/font/google";
import { Header, Navbar } from "./_components";
import "./globals.css";

const inter = Be_Vietnam_Pro({ weight: "300", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <main>
          <Navbar />
          <article>{children}</article>
        </main>
      </body>
    </html>
  );
}
